language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - python: 2.6
    dist: trusty
  - python: 2.7
  - python: 3.3
    dist: trusty
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.6
    arch: arm64
  - python: 3.7
  - python: 3.7
    arch: arm64
  - python: 3.8
  - python: 3.8
    arch: arm64
  - python: 3.9
  - python: 3.9
    arch: arm64
  - python: pypy
  - python: pypy3
  - python: 3.8
    services:
    - docker
    env:
    - BUILD_SDIST=true
    - BUILD_WHEEL=true
  - python: 3.8
    arch: arm64
    services:
    - docker
    env: BUILD_WHEEL=true
  - name: Python 2.7.17 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.17
  - name: Python 3.6.9 on macOS
    os: osx
    language: objective-c
    env: PYENV_VERSION=3.6.9
  - name: Python 3.7.5 on macOS
    os: osx
    osx_image: xcode11.3
    language: objective-c
    env: PYENV_VERSION=3.7.5
  - name: Python 3.8.0 on macOS
    os: osx
    osx_image: xcode11.3
    language: objective-c
    env: PYENV_VERSION=3.8.0
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  file:
  - dist/*.whl
  - dist/*.tar.gz
  file_glob: true
  on:
    repo: simplejson/simplejson
    tags: true
  skip_cleanup: true
  api_key:
    secure: FhcBCuL/33fsotaDLv157pQ0HpxYAXI9h4TNhT0CDgrh1i2J1m/hmJMqlrrn0j/E2TpYyXf1citLra6QrBP//FnFMGQ43el369tC3W9RPXYpfThzU6JcJecoWGQMMMiJgPLpOC7+tyDpphsNFKmySG/ITvX+OEZ4lzL8+1CWyRk=
